import { TAP_MS, TouchGestures } from './gestures'

describe('touch gestures', () => {
  it('two-finger and three-finger taps', () => {
    const g = new TouchGestures()
    expect(g.down(1, { x: 0, y: 0 }, 0)).toBe(null)
    expect(g.down(2, { x: 50, y: 0 }, 20)).toEqual({ kind: 'multi' })
    expect(g.up(1, 100)).toBe(null)
    expect(g.up(2, 120)).toEqual({ kind: 'tap', fingers: 2 })
    g.down(1, { x: 0, y: 0 }, 1000)
    g.down(2, { x: 10, y: 0 }, 1000)
    g.down(3, { x: 20, y: 0 }, 1010)
    g.up(1, 1100)
    g.up(2, 1100)
    expect(g.up(3, 1100)).toEqual({ kind: 'tap', fingers: 3 })
  })
  it('no tap when slow, moved or one finger', () => {
    const g = new TouchGestures()
    g.down(1, { x: 0, y: 0 }, 0)
    expect(g.up(1, 50)).toBe(null)
    g.down(1, { x: 0, y: 0 }, 0)
    g.down(2, { x: 50, y: 0 }, 0)
    g.up(1, TAP_MS + 10)
    expect(g.up(2, TAP_MS + 10)).toBe(null)
    g.down(1, { x: 0, y: 0 }, 0)
    g.down(2, { x: 50, y: 0 }, 0)
    g.move(2, { x: 90, y: 0 })
    g.up(1, 100)
    expect(g.up(2, 100)).toBe(null)
  })
  it('pinch reports both fingers and restarts when a finger lifts', () => {
    const g = new TouchGestures()
    g.down(1, { x: 0, y: 0 }, 0)
    expect(g.move(1, { x: 5, y: 0 })).toBe(null)
    g.down(2, { x: 100, y: 0 }, 0)
    const r = g.move(2, { x: 200, y: 0 })
    expect(r).toMatchObject({ kind: 'pinch', a0: { x: 5, y: 0 }, b0: { x: 100, y: 0 }, a1: { x: 5, y: 0 }, b1: { x: 200, y: 0 } })
    g.down(3, { x: 50, y: 50 }, 0)
    g.up(1, 0)
    const s = g.move(3, { x: 60, y: 50 })
    expect(s).toMatchObject({ kind: 'pinch', a0: { x: 200, y: 0 }, b0: { x: 50, y: 50 } })
    expect(s && s.kind === 'pinch' && r && r.kind === 'pinch' && s.epoch !== r.epoch).toBe(true)
  })
})
